#!/bin/bash -e

# dbus-launch is not installed by default in Fedora
# Do not list users in GDM3 login screen
# TODO: investigate how to move this into either /etc/gdm3/custom.conf or /etc/dconf/db/ibus.d
# TODO: not working
sudo -H dbus-run-session gsettings set org.gnome.login-screen disable-user-list true

# extra required packages
sudo dnf install -y gnome-tweaks dconf-editor

# install exta wallpapers
sudo dnf install -y f32-backgrounds-extras-gnome fedora-jam-backgrounds-gnome goddard-backgrounds-gnome laughlin-backgrounds-animated-gnome laughlin-backgrounds-extras-gnome laughlin-backgrounds-gnome lovelock-backgrounds-gnome lovelock-backgrounds-stripes-gnome schroedinger-cat-backgrounds-extras-gnome schroedinger-cat-backgrounds-gnome spherical-cow-backgrounds-extras-gnome spherical-cow-backgrounds-gnome verne-backgrounds-gnome

sudo dnf -y --refresh upgrade

