#!/bin/bash -e

# 24h clock
gsettings set org.gnome.desktop.interface clock-format '24h'

# Show date on clock
gsettings set org.gnome.desktop.interface clock-show-date true

# Show weekday
gsettings set org.gnome.desktop.interface clock-show-weekday true

