#!/bin/bash -e

# Increase watches for inotify-tools
sudo echo fs.inotify.max_user_watches=524288 | sudo tee /etc/sysctl.d/40-max-user-watches.conf

# swappiness
sudo sysctl -w vm.swappiness=10
sudo  vm.swappiness=10 | sudo tee /etc/sysctl.d/41-swappiness.conf

sudo sysctl --system
