#!/bin/bash -e

packagetype=${0##*-}

TMPFILE=$(mktemp)
trap "rm -rf $TMPFILE" EXIT

sudo dnf upgrade --refresh -y
sudo dnf check-update
cut -d\# -f1 ../files/packages-$packagetype |grep -v '^$' >$TMPFILE
sudo xargs -a $TMPFILE dnf install -y

# Post install for audio-video packages from RPM Fusion
sudo dnf group install -y multimedia --exclude=PackageKit-gstreamer-plugin
sudo dnf group install -y sound-and-video

sudo dnf autoremove -y

# To avoid the "System program problem detected"
#### rm -f /var/crash/*














